ShopTARge22/Models/KinderGartens/KindergartenCreateUpdateViewModel.cs
namespace ShopTARge22.Models.Kindergartens
{
    public class KindergartenCreateUpdateViewModel
    {
        public Guid? Id { get; set; }
        public string GroupName { get; set; }
        public int ChildrenCount { get; set; }
        public string KindergartenName { get; set; }
        public string Teacher { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

ShopTARge22/Models/KinderGartens/KindergartenDeleteViewModel.cs
namespace ShopTARge22.Models.Kindergartens
{
    public class KindergartenDeleteViewModel
    {
        public Guid? Id { get; set; }
        public string GroupName { get; set; }
        public int ChildrenCount { get; set; }
        public string KindergartenName { get; set; }
        public string Teacher { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

ShopTARge22/Models/KinderGartens/KindergartenDetailsViewModel.cs
namespace ShopTARge22.Models.Kindergartens
{
    public class KindergartenDetailsViewModel
    {
        public Guid? Id { get; set; }
        public string GroupName { get; set; }
        public int ChildrenCount { get; set; }
        public string KindergartenName { get; set; }
        public string Teacher { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

ShopTARge22/Models/KinderGartens/KindergartenIndexViewModel.cs
namespace ShopTARge22.Models.Kindergartens
{
    public class KindergartenIndexViewModel
    {
        public Guid? Id { get; set; }
        public string GroupName { get; set; }
        public string KindergartenName { get; set; }
        public string Teacher {  get; set; }

    }
}

 

ShopTARge22/Controllers/KindergartensController.cs
using Microsoft.AspNetCore.Mvc;
using ShopTARge22.Core.Dto;
using ShopTARge22.Core.ServiceInterface;
using ShopTARge22.Data;
using ShopTARge22.Models.Kindergartens;

namespace ShopTARge22.Controllers
{
    public class KindergartensController : Controller
    {
        private readonly ShopTARge22Context _context;
        private readonly IKindergartenServices _kindergartenServices;

        public KindergartensController
            (
            ShopTARge22Context context,
            IKindergartenServices kindergartenServices
            )
        {
            _context = context;
            _kindergartenServices = kindergartenServices;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var result = _context.Kindergartens
                .Select(x => new KindergartenIndexViewModel
                {
                    Id = x.Id,
                    GroupName = x.GroupName,
                    KindergartenName = x.KindergartenName,
                    Teacher = x.Teacher,
                });
            return View(result);
        }

        [HttpGet]
        public IActionResult Create()
        {
            KindergartenCreateUpdateViewModel vm = new();
            return View("CreateUpdate", vm);
        }

        [HttpPost]
        public async Task<IActionResult>Create (KindergartenCreateUpdateViewModel vm)
        {
            var dto = new KindergartenDto()
            {
                Id= vm.Id,
                GroupName= vm.GroupName,
                ChildrenCount = vm.ChildrenCount,
                KindergartenName= vm.KindergartenName,
                Teacher = vm.Teacher,
                CreatedAt = vm.CreatedAt,
                UpdatedAt = vm.UpdatedAt,
            };
            var result = await _kindergartenServices.Create(dto);
            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index), vm);
        }

        [HttpGet]
        public async Task<IActionResult>Update(Guid id)
        {
            var kindergarten = await _kindergartenServices.DetailsAsync(id);
            if (kindergarten == null)
            {
                return NotFound();
            }

            var vm = new KindergartenCreateUpdateViewModel();
            vm.Id = kindergarten.Id;
            vm.GroupName = kindergarten.GroupName;
            vm.ChildrenCount = kindergarten.ChildrenCount;
            vm.KindergartenName = kindergarten.KindergartenName;
            vm.Teacher = kindergarten.Teacher;
            vm.CreatedAt = kindergarten.CreatedAt;
            vm.UpdatedAt = kindergarten.UpdatedAt;

            return View("CreateUpdate", vm);
        }

        [HttpPost]
        public async Task<IActionResult>Update(KindergartenCreateUpdateViewModel vm)
        {
            var dto = new KindergartenDto()
            {
                Id = vm.Id,
                GroupName = vm.GroupName,
                ChildrenCount = vm.ChildrenCount,
                KindergartenName = vm.KindergartenName,
                Teacher = vm.Teacher,
                CreatedAt = vm.CreatedAt,
                UpdatedAt = vm.UpdatedAt,
            };
            var result = await _kindergartenServices.Update(dto);
            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index), vm);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var kindergarten = await _kindergartenServices.DetailsAsync(id);
            if (kindergarten == null)
            {
                return NotFound();
            }

            var vm = new KindergartenDetailsViewModel();
            vm.Id = kindergarten.Id;
            vm.GroupName = kindergarten.GroupName;
            vm.ChildrenCount = kindergarten.ChildrenCount;
            vm.KindergartenName = kindergarten.KindergartenName;
            vm.Teacher = kindergarten.Teacher;
            vm.CreatedAt = kindergarten.CreatedAt;
            vm.UpdatedAt = kindergarten.UpdatedAt;

            return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var kindergarten = await _kindergartenServices.DetailsAsync(id);
            if (kindergarten == null)
            {
                return NotFound();
            }

            var vm = new KindergartenDeleteViewModel();
            vm.Id = kindergarten.Id;
            vm.GroupName= kindergarten.GroupName;
            vm.ChildrenCount= kindergarten.ChildrenCount;
            vm.KindergartenName = kindergarten.KindergartenName;
            vm.Teacher= kindergarten.Teacher;
            vm.CreatedAt= kindergarten.CreatedAt;
            vm.UpdatedAt= kindergarten.UpdatedAt;

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult>DeleteConfirmation(Guid id)
        {
            var kindergartenId = await _kindergartenServices.Delete(id);
            if (kindergartenId == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

ShopTARge22/Views/Kindergartens/CreateUpdate.cshtml
@model ShopTARge22.Models.Kindergartens.KindergartenCreateUpdateViewModel;

@if(Model.Id.HasValue)
{
    <h1>Update</h1>
}
else
{
    <h1>Create</h1>
}

<div>
    <form method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <input asp-for="CreatedAt" type="hidden" />
        <input asp-for="UpdatedAt" type="hidden" />

        <div class="form-group-row">
            <label asp-for="GroupName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="GroupName" class="form-control" />
            </div>
        </div>

        <div class="form-group-row">
            <label asp-for="ChildrenCount" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="ChildrenCount" class="form-control" />
            </div>
        </div>

        <div class="form-group-row">
            <label asp-for="KindergartenName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="KindergartenName" class="form-control" />
            </div>
        </div>

        <div class="form-group-row">
            <label asp-for="Teacher" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Teacher" class="form-control" />
            </div>
        </div>

        <hr/>
        @if(Model.Id.HasValue)
        {
            <input asp-action="update" asp-controller="kindergartens" type="submit" class="btn btn-success" value="Update" />
        }
        else
        {
            <input asp-action="create" asp-controller="kindergartens" type="submit" class="btn btn-secondary" value="Create" />
        }

        <a asp-action="index" class="btn btn-outline-info">Index</a>


    </form>
</div>

ShopTARge22/Views/Kindergartens/Delete.cshtml
@model ShopTARge22.Models.Kindergartens.KindergartenDeleteViewModel;

<h1>Delete</h1>

<div>
    <h4>Kindergartens</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Id)
        </div>

        <div class="form-group row">
            <label asp-for="GroupName" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.GroupName)
        </div>

        <div class="form-group row">
            <label asp-for="ChildrenCount" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.ChildrenCount)
        </div>

        <div class="form-group row">
            <label asp-for="KindergartenName" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.KindergartenName)
        </div>

        <div class="form-group row">
            <label asp-for="Teacher" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Teacher)
        </div>
    </dl>

    <form asp-action="DeleteConfirmation">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-warning" />
        <a asp-action="Index" asp-controller="kindergartens" class="btn btn-dark">Back</a>
    </form>
</div>

ShopTARge22/Views/Kindergartens/Details.cshtml
@model ShopTARge22.Models.Kindergartens.KindergartenDetailsViewModel;

<h1>Details</h1>

<h4>Kindergartens</h4>
<hr />
<dl class="row">
    <div class="form-group row">
        <label asp-for="Id" class="col-sm-2 col-form-label"></label>
        @Html.DisplayFor(model => model.Id)
    </div>

    <div class="form-group row">
        <label asp-for="GroupName" class="col-sm-2 col-form-label"></label>
        @Html.DisplayFor(model => model.GroupName)
    </div>

    <div class="form-group row">
        <label asp-for="ChildrenCount" class="col-sm-2 col-form-label"></label>
        @Html.DisplayFor(model => model.ChildrenCount)
    </div>

    <div class="form-group row">
        <label asp-for="KindergartenName" class="col-sm-2 col-form-label"></label>
        @Html.DisplayFor(model => model.KindergartenName)
    </div>

    <div class="form-group row">
        <label asp-for="Teacher" class="col-sm-2 col-form-label"></label>
        @Html.DisplayFor(model => model.Teacher)
    </div>

    <div class="form-group row">
        <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
        @Html.DisplayFor(model => model.CreatedAt)
    </div>

    <div class="form-group row">
        <label asp-for="UpdatedAt" class="col-sm-2 col-form-label"></label>
        @Html.DisplayFor(model => model.UpdatedAt)
    </div>

</dl>
<a asp-action="Index" asp-controller="kindergartens" class="btn btn-dark">Back</a>
</div>

ShopTARge22/Views/Kindergartens/Index.cshtml
@model IEnumerable<ShopTARge22.Models.Kindergartens.KindergartenIndexViewModel>;

@{
    int rowNumber = 1;
}
<div>
    <a asp-action="create" asp-controller="Kindergartens" type="submit" class="btn btn-secondary">Create</a>
</div>

<div class="h1">
    Kindergarten
</div>
<form method="post">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Nr</th>
                <th scope="col">GroupName</th>
                <th scope="col">KindergartenName</th>
                <th scope="col">Teacher</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var kindergarten in Model)
            {
                <tr>
                    <td>@rowNumber</td>
                    <td>@kindergarten.GroupName</td>
                    <td>@kindergarten.KindergartenName</td>
                    <td>@kindergarten.Teacher</td>
                    <td>
                        <a asp-action="details" asp-controller="kindergartens" asp-route-id="@kindergarten.Id" class="btn btn-outline-success">Details</a>
                        <a asp-action="update" asp-controller="kindergartens" asp-route-id="@kindergarten.Id" class="btn btn-outline-secondary">Update</a>
                        <a asp-action="delete" asp-controller="kindergartens" asp-route-id="@kindergarten.Id" class="btn btn-outline-warning">Delete</a>

                    </td>
                </tr>

                rowNumber += 1;
            }
        </tbody>
    </table>
</form>